server:
  port: 12000

spring:
  application:
    name: tensquare-config
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/chuanzhiliubei/tensquare-config.git
  rabbitmq:
     host: 47.106.120.224
management: #暴露触发消息总线的地址
  endpoints:
   web:
      exposure:
        include: bus-refresh
