server: 
  port: 9005
spring: 
  application:  
    name: tensquare-gathering #指定服务名
  datasource:  
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.107.71.209:3306/tensquare_gathering?characterEncoding=UTF-8&useSSL=false
    username: root
    password: tensquare123456
  jpa: 
    database: MySQL
    show-sql: true
