server: 
  port: 9008
spring: 
  application:  
    name: tensquare-user #指定服务名
  datasource:  
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.120.226:3306/tensquare_user?characterEncoding=UTF-8&useSSL=false
    username: root
    password: tensquare123456
  jpa: 
    database: MySQL
    show-sql: true

  redis:
      host: 192.168.120.225
  rabbitmq:
      host: 192.168.120.225
jwt:
  config:
     key: helloKitty
     ttl: 3600000

eureka:
  client:
    service‐url:
      defaultZone: http://localhost:6868/eureka
  instance:
     prefer-ip-address: true

